//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipboardZanager.Strings.SettingsAboutUserControl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsAboutUserControl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsAboutUserControl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClipboardZanager.Strings.SettingsAboutUserControl.SettingsAboutUserControl", typeof(SettingsAboutUserControl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project is Open Source. Explore the source and contribute here..
        /// </summary>
        internal static string Contribute {
            get {
                return ResourceManager.GetString("Contribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THIRD-PARTY SOFTWARE
        ///
        ///- MvvmLight (Laurent Bugnion)
        ///- Json.Net (James Newton-King)
        ///- DropBox API (DropBox, Inc.)
        ///- OneDrive SDK (Microsoft Corporation)
        ///
        ///SPECIAL THANKS TO
        ///
        ///Jean-Edouard Chamalet, Ky Van Doan, Miriam Djebloun for their advice about the user interface.
        ///Jérémie Rabusseau, Johnathan Abraham, Paul Fasola, Valentin Michalak for their feedbacks during the development phase.
        ///
        ///TRANSLATORS
        ///
        ///- French : Etienne Baudoux.
        /// </summary>
        internal static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string CreditButton {
            get {
                return ResourceManager.GetString("CreditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CreditButton_Confirm {
            get {
                return ResourceManager.GetString("CreditButton_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        internal static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send the logs to the author.
        /// </summary>
        internal static string SendLog {
            get {
                return ResourceManager.GetString("SendLog", resourceCulture);
            }
        }
    }
}
