// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System.Collections.Generic;
using System.Globalization;
using System.Threading;
using System.Windows;
using GalaSoft.MvvmLight;

namespace ClipboardZanager.Strings
{
    internal class LanguageManager : ViewModelBase
    {
        #region Fields

        private static LanguageManager _languageManager;
		
        private FirstStartWindowStrings _FirstStartWindow => new FirstStartWindowStrings();
        private MainWindowStrings _MainWindow => new MainWindowStrings();
        private PasteBarWindowStrings _PasteBarWindow => new PasteBarWindowStrings();
        private SettingsAboutUserControlStrings _SettingsAboutUserControl => new SettingsAboutUserControlStrings();
        private SettingsDataUserControlStrings _SettingsDataUserControl => new SettingsDataUserControlStrings();
        private SettingsGeneralUserControlStrings _SettingsGeneralUserControl => new SettingsGeneralUserControlStrings();
        private SettingsNotificationsUserControlStrings _SettingsNotificationsUserControl => new SettingsNotificationsUserControlStrings();
        private SettingsSecurityUserControlStrings _SettingsSecurityUserControl => new SettingsSecurityUserControlStrings();
        private SettingsSynchronizationUserControlStrings _SettingsSynchronizationUserControl => new SettingsSynchronizationUserControlStrings();
        private SettingsWindowStrings _SettingsWindow => new SettingsWindowStrings();

        #endregion

        #region Properties

        /// <summary>
        /// Gets if the text must be written from left to right or from right to left.
        /// </summary>
        public FlowDirection FlowDirection { get; private set; }

        /// <summary>
        /// Gets the <see cref="FirstStartWindowStrings"/>.
        /// </summary>
        public FirstStartWindowStrings FirstStartWindow => _FirstStartWindow;

        /// <summary>
        /// Gets the <see cref="MainWindowStrings"/>.
        /// </summary>
        public MainWindowStrings MainWindow => _MainWindow;

        /// <summary>
        /// Gets the <see cref="PasteBarWindowStrings"/>.
        /// </summary>
        public PasteBarWindowStrings PasteBarWindow => _PasteBarWindow;

        /// <summary>
        /// Gets the <see cref="SettingsAboutUserControlStrings"/>.
        /// </summary>
        public SettingsAboutUserControlStrings SettingsAboutUserControl => _SettingsAboutUserControl;

        /// <summary>
        /// Gets the <see cref="SettingsDataUserControlStrings"/>.
        /// </summary>
        public SettingsDataUserControlStrings SettingsDataUserControl => _SettingsDataUserControl;

        /// <summary>
        /// Gets the <see cref="SettingsGeneralUserControlStrings"/>.
        /// </summary>
        public SettingsGeneralUserControlStrings SettingsGeneralUserControl => _SettingsGeneralUserControl;

        /// <summary>
        /// Gets the <see cref="SettingsNotificationsUserControlStrings"/>.
        /// </summary>
        public SettingsNotificationsUserControlStrings SettingsNotificationsUserControl => _SettingsNotificationsUserControl;

        /// <summary>
        /// Gets the <see cref="SettingsSecurityUserControlStrings"/>.
        /// </summary>
        public SettingsSecurityUserControlStrings SettingsSecurityUserControl => _SettingsSecurityUserControl;

        /// <summary>
        /// Gets the <see cref="SettingsSynchronizationUserControlStrings"/>.
        /// </summary>
        public SettingsSynchronizationUserControlStrings SettingsSynchronizationUserControl => _SettingsSynchronizationUserControl;

        /// <summary>
        /// Gets the <see cref="SettingsWindowStrings"/>.
        /// </summary>
        public SettingsWindowStrings SettingsWindow => _SettingsWindow;

        #endregion

        #region Methods

        /// <summary>
        /// Gets an instance of <see cref="LanguageManager"/>.
        /// </summary>
        internal static LanguageManager GetInstance()
        {
            return _languageManager ?? (_languageManager = new LanguageManager());
        }

        /// <summary>
        /// Retrieves the current culture.
        /// </summary>
        internal CultureInfo GetCurrentCulture()
        {
            return Thread.CurrentThread.CurrentCulture;
        }

        /// <summary>
        /// Change the current culture of the application
        /// </summary>
        internal void SetCurrentCulture(CultureInfo culture)
        {
            Thread.CurrentThread.CurrentCulture = culture;
            Thread.CurrentThread.CurrentUICulture = culture;
            if (culture.TextInfo.IsRightToLeft)
            {
                FlowDirection = FlowDirection.RightToLeft;
            }
            else
            {
                FlowDirection = FlowDirection.LeftToRight;
            }

            RaisePropertyChanged(string.Empty);
        }

        /// <summary>
        /// Retrieves the list of available culture for this application
        /// </summary>
        /// <returns>A list of available <see cref="CultureInfo"/></returns>
        internal List<CultureInfo> GetAvailableCultures()
        {
            var result = new List<CultureInfo>();
            var rm = Strings.MainWindow.MainWindow.ResourceManager;
            var cultures = CultureInfo.GetCultures(CultureTypes.AllCultures);

            foreach (var culture in cultures)
            {
                if (culture.Equals(CultureInfo.InvariantCulture))
                {
                    continue;
                }

                var rs = rm.GetResourceSet(culture, true, false);
                if (rs != null)
                {
                    result.Add(culture);
                }
            }

            return result;
        }

        #endregion
    }

    internal class FirstStartWindowStrings : ViewModelBase
    {
        #region Properties

        /// <summary>
        /// Gets the resource GotIt.
        /// </summary>
        public string GotIt => FirstStartWindow.FirstStartWindow.GotIt;

        /// <summary>
        /// Gets the resource HowToPaste_Title.
        /// </summary>
        public string HowToPaste_Title => FirstStartWindow.FirstStartWindow.HowToPaste_Title;

        /// <summary>
        /// Gets the resource HowToPaste_TitleHelpText.
        /// </summary>
        public string HowToPaste_TitleHelpText => FirstStartWindow.FirstStartWindow.HowToPaste_TitleHelpText;

        /// <summary>
        /// Gets the resource HowToPaste_Use.
        /// </summary>
        public string HowToPaste_Use => FirstStartWindow.FirstStartWindow.HowToPaste_Use;

        /// <summary>
        /// Gets the resource MigrationCompleted.
        /// </summary>
        public string MigrationCompleted => FirstStartWindow.FirstStartWindow.MigrationCompleted;

        /// <summary>
        /// Gets the resource MigrationFailed.
        /// </summary>
        public string MigrationFailed => FirstStartWindow.FirstStartWindow.MigrationFailed;

        /// <summary>
        /// Gets the resource MigrationInProgress.
        /// </summary>
        public string MigrationInProgress => FirstStartWindow.FirstStartWindow.MigrationInProgress;

        /// <summary>
        /// Gets the resource Security_Description.
        /// </summary>
        public string Security_Description => FirstStartWindow.FirstStartWindow.Security_Description;

        /// <summary>
        /// Gets the resource Security_Title.
        /// </summary>
        public string Security_Title => FirstStartWindow.FirstStartWindow.Security_Title;

        /// <summary>
        /// Gets the resource Synchronization_Description.
        /// </summary>
        public string Synchronization_Description => FirstStartWindow.FirstStartWindow.Synchronization_Description;

        /// <summary>
        /// Gets the resource Synchronization_Title.
        /// </summary>
        public string Synchronization_Title => FirstStartWindow.FirstStartWindow.Synchronization_Title;

        /// <summary>
        /// Gets the resource Welcome_SelectLanguage.
        /// </summary>
        public string Welcome_SelectLanguage => FirstStartWindow.FirstStartWindow.Welcome_SelectLanguage;

        /// <summary>
        /// Gets the resource Welcome_Text.
        /// </summary>
        public string Welcome_Text => FirstStartWindow.FirstStartWindow.Welcome_Text;

        /// <summary>
        /// Gets the resource Welcome_Title.
        /// </summary>
        public string Welcome_Title => FirstStartWindow.FirstStartWindow.Welcome_Title;

        /// <summary>
        /// Gets the resource WhatsNew_Title.
        /// </summary>
        public string WhatsNew_Title => FirstStartWindow.FirstStartWindow.WhatsNew_Title;

        /// <summary>
        /// Gets the resource WindowAutomationName.
        /// </summary>
        public string WindowAutomationName => FirstStartWindow.FirstStartWindow.WindowAutomationName;

        #endregion
    }

    internal class MainWindowStrings : ViewModelBase
    {
        #region Properties

        /// <summary>
        /// Gets the resource ApplicationTitle.
        /// </summary>
        public string ApplicationTitle => MainWindow.MainWindow.ApplicationTitle;

        /// <summary>
        /// Gets the resource Cancel.
        /// </summary>
        public string Cancel => MainWindow.MainWindow.Cancel;

        /// <summary>
        /// Gets the resource CreditCardDetectedButSaved_Text.
        /// </summary>
        public string CreditCardDetectedButSaved_Text => MainWindow.MainWindow.CreditCardDetectedButSaved_Text;

        /// <summary>
        /// Gets the resource CreditCardDetectedButSaved_Title.
        /// </summary>
        public string CreditCardDetectedButSaved_Title => MainWindow.MainWindow.CreditCardDetectedButSaved_Title;

        /// <summary>
        /// Gets the resource CreditCardDetected_Text.
        /// </summary>
        public string CreditCardDetected_Text => MainWindow.MainWindow.CreditCardDetected_Text;

        /// <summary>
        /// Gets the resource CreditCardDetected_Title.
        /// </summary>
        public string CreditCardDetected_Title => MainWindow.MainWindow.CreditCardDetected_Title;

        /// <summary>
        /// Gets the resource CreditCardSaved_Text.
        /// </summary>
        public string CreditCardSaved_Text => MainWindow.MainWindow.CreditCardSaved_Text;

        /// <summary>
        /// Gets the resource CreditCardSaved_Title.
        /// </summary>
        public string CreditCardSaved_Title => MainWindow.MainWindow.CreditCardSaved_Title;

        /// <summary>
        /// Gets the resource FlipView_Next.
        /// </summary>
        public string FlipView_Next => MainWindow.MainWindow.FlipView_Next;

        /// <summary>
        /// Gets the resource FlipView_NextHelpText.
        /// </summary>
        public string FlipView_NextHelpText => MainWindow.MainWindow.FlipView_NextHelpText;

        /// <summary>
        /// Gets the resource FlipView_Previous.
        /// </summary>
        public string FlipView_Previous => MainWindow.MainWindow.FlipView_Previous;

        /// <summary>
        /// Gets the resource FlipView_PreviousHelpText.
        /// </summary>
        public string FlipView_PreviousHelpText => MainWindow.MainWindow.FlipView_PreviousHelpText;

        /// <summary>
        /// Gets the resource Menu_Paste_Text.
        /// </summary>
        public string Menu_Paste_Text => MainWindow.MainWindow.Menu_Paste_Text;

        /// <summary>
        /// Gets the resource Menu_Paste_Tooltip.
        /// </summary>
        public string Menu_Paste_Tooltip => MainWindow.MainWindow.Menu_Paste_Tooltip;

        /// <summary>
        /// Gets the resource Menu_Quit_Text.
        /// </summary>
        public string Menu_Quit_Text => MainWindow.MainWindow.Menu_Quit_Text;

        /// <summary>
        /// Gets the resource Menu_Quit_Tooltip.
        /// </summary>
        public string Menu_Quit_Tooltip => MainWindow.MainWindow.Menu_Quit_Tooltip;

        /// <summary>
        /// Gets the resource Menu_Settings_Text.
        /// </summary>
        public string Menu_Settings_Text => MainWindow.MainWindow.Menu_Settings_Text;

        /// <summary>
        /// Gets the resource Menu_Settings_Tooltip.
        /// </summary>
        public string Menu_Settings_Tooltip => MainWindow.MainWindow.Menu_Settings_Tooltip;

        /// <summary>
        /// Gets the resource Menu_Synchronize_Text.
        /// </summary>
        public string Menu_Synchronize_Text => MainWindow.MainWindow.Menu_Synchronize_Text;

        /// <summary>
        /// Gets the resource Menu_Synchronize_Tooltip.
        /// </summary>
        public string Menu_Synchronize_Tooltip => MainWindow.MainWindow.Menu_Synchronize_Tooltip;

        /// <summary>
        /// Gets the resource Message_Quit.
        /// </summary>
        public string Message_Quit => MainWindow.MainWindow.Message_Quit;

        /// <summary>
        /// Gets the resource PasswordDetectedButSaved_Text.
        /// </summary>
        public string PasswordDetectedButSaved_Text => MainWindow.MainWindow.PasswordDetectedButSaved_Text;

        /// <summary>
        /// Gets the resource PasswordDetectedButSaved_Title.
        /// </summary>
        public string PasswordDetectedButSaved_Title => MainWindow.MainWindow.PasswordDetectedButSaved_Title;

        /// <summary>
        /// Gets the resource PasswordDetected_Text.
        /// </summary>
        public string PasswordDetected_Text => MainWindow.MainWindow.PasswordDetected_Text;

        /// <summary>
        /// Gets the resource PasswordDetected_Title.
        /// </summary>
        public string PasswordDetected_Title => MainWindow.MainWindow.PasswordDetected_Title;

        /// <summary>
        /// Gets the resource PasswordSaved_Text.
        /// </summary>
        public string PasswordSaved_Text => MainWindow.MainWindow.PasswordSaved_Text;

        /// <summary>
        /// Gets the resource PasswordSaved_Title.
        /// </summary>
        public string PasswordSaved_Title => MainWindow.MainWindow.PasswordSaved_Title;

        /// <summary>
        /// Gets the resource SynchronizationFailed_Text.
        /// </summary>
        public string SynchronizationFailed_Text => MainWindow.MainWindow.SynchronizationFailed_Text;

        /// <summary>
        /// Gets the resource SynchronizationFailed_Title.
        /// </summary>
        public string SynchronizationFailed_Title => MainWindow.MainWindow.SynchronizationFailed_Title;

        #endregion
    }

    internal class PasteBarWindowStrings : ViewModelBase
    {
        #region Properties

        /// <summary>
        /// Gets the resource Back.
        /// </summary>
        public string Back => PasteBarWindow.PasteBarWindow.Back;

        /// <summary>
        /// Gets the resource Close.
        /// </summary>
        public string Close => PasteBarWindow.PasteBarWindow.Close;

        /// <summary>
        /// Gets the resource Close_AccessibilityKey.
        /// </summary>
        public string Close_AccessibilityKey => PasteBarWindow.PasteBarWindow.Close_AccessibilityKey;

        /// <summary>
        /// Gets the resource Copy.
        /// </summary>
        public string Copy => PasteBarWindow.PasteBarWindow.Copy;

        /// <summary>
        /// Gets the resource Copy_Tooltip.
        /// </summary>
        public string Copy_Tooltip => PasteBarWindow.PasteBarWindow.Copy_Tooltip;

        /// <summary>
        /// Gets the resource DataColor.
        /// </summary>
        public string DataColor => PasteBarWindow.PasteBarWindow.DataColor;

        /// <summary>
        /// Gets the resource DataFile.
        /// </summary>
        public string DataFile => PasteBarWindow.PasteBarWindow.DataFile;

        /// <summary>
        /// Gets the resource DataHelpText.
        /// </summary>
        public string DataHelpText => PasteBarWindow.PasteBarWindow.DataHelpText;

        /// <summary>
        /// Gets the resource DataImage.
        /// </summary>
        public string DataImage => PasteBarWindow.PasteBarWindow.DataImage;

        /// <summary>
        /// Gets the resource DataLink.
        /// </summary>
        public string DataLink => PasteBarWindow.PasteBarWindow.DataLink;

        /// <summary>
        /// Gets the resource DataText.
        /// </summary>
        public string DataText => PasteBarWindow.PasteBarWindow.DataText;

        /// <summary>
        /// Gets the resource DataUnknow.
        /// </summary>
        public string DataUnknow => PasteBarWindow.PasteBarWindow.DataUnknow;

        /// <summary>
        /// Gets the resource Delete.
        /// </summary>
        public string Delete => PasteBarWindow.PasteBarWindow.Delete;

        /// <summary>
        /// Gets the resource DeleteAll.
        /// </summary>
        public string DeleteAll => PasteBarWindow.PasteBarWindow.DeleteAll;

        /// <summary>
        /// Gets the resource DeleteAllConfirm.
        /// </summary>
        public string DeleteAllConfirm => PasteBarWindow.PasteBarWindow.DeleteAllConfirm;

        /// <summary>
        /// Gets the resource DeleteAll_Tooltip.
        /// </summary>
        public string DeleteAll_Tooltip => PasteBarWindow.PasteBarWindow.DeleteAll_Tooltip;

        /// <summary>
        /// Gets the resource DeleteConfirm.
        /// </summary>
        public string DeleteConfirm => PasteBarWindow.PasteBarWindow.DeleteConfirm;

        /// <summary>
        /// Gets the resource Delete_ToolTip.
        /// </summary>
        public string Delete_ToolTip => PasteBarWindow.PasteBarWindow.Delete_ToolTip;

        /// <summary>
        /// Gets the resource ErrorGeneratingThumbnail.
        /// </summary>
        public string ErrorGeneratingThumbnail => PasteBarWindow.PasteBarWindow.ErrorGeneratingThumbnail;

        /// <summary>
        /// Gets the resource Favorite.
        /// </summary>
        public string Favorite => PasteBarWindow.PasteBarWindow.Favorite;

        /// <summary>
        /// Gets the resource Filter_Files.
        /// </summary>
        public string Filter_Files => PasteBarWindow.PasteBarWindow.Filter_Files;

        /// <summary>
        /// Gets the resource Filter_Images.
        /// </summary>
        public string Filter_Images => PasteBarWindow.PasteBarWindow.Filter_Images;

        /// <summary>
        /// Gets the resource Filter_Link.
        /// </summary>
        public string Filter_Link => PasteBarWindow.PasteBarWindow.Filter_Link;

        /// <summary>
        /// Gets the resource Filter_Text.
        /// </summary>
        public string Filter_Text => PasteBarWindow.PasteBarWindow.Filter_Text;

        /// <summary>
        /// Gets the resource More.
        /// </summary>
        public string More => PasteBarWindow.PasteBarWindow.More;

        /// <summary>
        /// Gets the resource NoPresentData.
        /// </summary>
        public string NoPresentData => PasteBarWindow.PasteBarWindow.NoPresentData;

        /// <summary>
        /// Gets the resource NoSearchResult.
        /// </summary>
        public string NoSearchResult => PasteBarWindow.PasteBarWindow.NoSearchResult;

        /// <summary>
        /// Gets the resource NoThumbnail.
        /// </summary>
        public string NoThumbnail => PasteBarWindow.PasteBarWindow.NoThumbnail;

        /// <summary>
        /// Gets the resource Paste.
        /// </summary>
        public string Paste => PasteBarWindow.PasteBarWindow.Paste;

        /// <summary>
        /// Gets the resource Paste_Tooltip.
        /// </summary>
        public string Paste_Tooltip => PasteBarWindow.PasteBarWindow.Paste_Tooltip;

        /// <summary>
        /// Gets the resource SearchHelpText.
        /// </summary>
        public string SearchHelpText => PasteBarWindow.PasteBarWindow.SearchHelpText;

        /// <summary>
        /// Gets the resource Share.
        /// </summary>
        public string Share => PasteBarWindow.PasteBarWindow.Share;

        /// <summary>
        /// Gets the resource Synchronize.
        /// </summary>
        public string Synchronize => PasteBarWindow.PasteBarWindow.Synchronize;

        /// <summary>
        /// Gets the resource TimeSpan.
        /// </summary>
        public string TimeSpan => PasteBarWindow.PasteBarWindow.TimeSpan;

        /// <summary>
        /// Gets the resource TimeSpan_Ago.
        /// </summary>
        public string TimeSpan_Ago => PasteBarWindow.PasteBarWindow.TimeSpan_Ago;

        /// <summary>
        /// Gets the resource TimeSpan_Days.
        /// </summary>
        public string TimeSpan_Days => PasteBarWindow.PasteBarWindow.TimeSpan_Days;

        /// <summary>
        /// Gets the resource TimeSpan_Hour.
        /// </summary>
        public string TimeSpan_Hour => PasteBarWindow.PasteBarWindow.TimeSpan_Hour;

        /// <summary>
        /// Gets the resource TimeSpan_Hours.
        /// </summary>
        public string TimeSpan_Hours => PasteBarWindow.PasteBarWindow.TimeSpan_Hours;

        /// <summary>
        /// Gets the resource TimeSpan_LessThanAMinute.
        /// </summary>
        public string TimeSpan_LessThanAMinute => PasteBarWindow.PasteBarWindow.TimeSpan_LessThanAMinute;

        /// <summary>
        /// Gets the resource TimeSpan_Minutes.
        /// </summary>
        public string TimeSpan_Minutes => PasteBarWindow.PasteBarWindow.TimeSpan_Minutes;

        /// <summary>
        /// Gets the resource TimeSpan_Yesterday.
        /// </summary>
        public string TimeSpan_Yesterday => PasteBarWindow.PasteBarWindow.TimeSpan_Yesterday;

        /// <summary>
        /// Gets the resource WindowAutomationName.
        /// </summary>
        public string WindowAutomationName => PasteBarWindow.PasteBarWindow.WindowAutomationName;

        #endregion
    }

    internal class SettingsAboutUserControlStrings : ViewModelBase
    {
        #region Properties

        /// <summary>
        /// Gets the resource Contribute.
        /// </summary>
        public string Contribute => SettingsAboutUserControl.SettingsAboutUserControl.Contribute;

        /// <summary>
        /// Gets the resource Credit.
        /// </summary>
        public string Credit => SettingsAboutUserControl.SettingsAboutUserControl.Credit;

        /// <summary>
        /// Gets the resource CreditButton.
        /// </summary>
        public string CreditButton => SettingsAboutUserControl.SettingsAboutUserControl.CreditButton;

        /// <summary>
        /// Gets the resource CreditButton_Confirm.
        /// </summary>
        public string CreditButton_Confirm => SettingsAboutUserControl.SettingsAboutUserControl.CreditButton_Confirm;

        /// <summary>
        /// Gets the resource Privacy.
        /// </summary>
        public string Privacy => SettingsAboutUserControl.SettingsAboutUserControl.Privacy;

        /// <summary>
        /// Gets the resource SendLog.
        /// </summary>
        public string SendLog => SettingsAboutUserControl.SettingsAboutUserControl.SendLog;

        #endregion
    }

    internal class SettingsDataUserControlStrings : ViewModelBase
    {
        #region Properties

        /// <summary>
        /// Gets the resource DataToKeep.
        /// </summary>
        public string DataToKeep => SettingsDataUserControl.SettingsDataUserControl.DataToKeep;

        /// <summary>
        /// Gets the resource Days.
        /// </summary>
        public string Days => SettingsDataUserControl.SettingsDataUserControl.Days;

        /// <summary>
        /// Gets the resource Excel.
        /// </summary>
        public string Excel => SettingsDataUserControl.SettingsDataUserControl.Excel;

        /// <summary>
        /// Gets the resource ExpireLimit.
        /// </summary>
        public string ExpireLimit => SettingsDataUserControl.SettingsDataUserControl.ExpireLimit;

        /// <summary>
        /// Gets the resource File.
        /// </summary>
        public string File => SettingsDataUserControl.SettingsDataUserControl.File;

        /// <summary>
        /// Gets the resource Image.
        /// </summary>
        public string Image => SettingsDataUserControl.SettingsDataUserControl.Image;

        /// <summary>
        /// Gets the resource Outlook.
        /// </summary>
        public string Outlook => SettingsDataUserControl.SettingsDataUserControl.Outlook;

        /// <summary>
        /// Gets the resource Photoshop.
        /// </summary>
        public string Photoshop => SettingsDataUserControl.SettingsDataUserControl.Photoshop;

        /// <summary>
        /// Gets the resource PowerPoint.
        /// </summary>
        public string PowerPoint => SettingsDataUserControl.SettingsDataUserControl.PowerPoint;

        /// <summary>
        /// Gets the resource Reboot.
        /// </summary>
        public string Reboot => SettingsDataUserControl.SettingsDataUserControl.Reboot;

        /// <summary>
        /// Gets the resource Text.
        /// </summary>
        public string Text => SettingsDataUserControl.SettingsDataUserControl.Text;

        /// <summary>
        /// Gets the resource WhatToKeep.
        /// </summary>
        public string WhatToKeep => SettingsDataUserControl.SettingsDataUserControl.WhatToKeep;

        /// <summary>
        /// Gets the resource Word.
        /// </summary>
        public string Word => SettingsDataUserControl.SettingsDataUserControl.Word;

        #endregion
    }

    internal class SettingsGeneralUserControlStrings : ViewModelBase
    {
        #region Properties

        /// <summary>
        /// Gets the resource ChangeHotKey.
        /// </summary>
        public string ChangeHotKey => SettingsGeneralUserControl.SettingsGeneralUserControl.ChangeHotKey;

        /// <summary>
        /// Gets the resource ClosePasteBarWhenMouseIsAway.
        /// </summary>
        public string ClosePasteBarWhenMouseIsAway => SettingsGeneralUserControl.SettingsGeneralUserControl.ClosePasteBarWhenMouseIsAway;

        /// <summary>
        /// Gets the resource ClosePasteBarWithHotKey.
        /// </summary>
        public string ClosePasteBarWithHotKey => SettingsGeneralUserControl.SettingsGeneralUserControl.ClosePasteBarWithHotKey;

        /// <summary>
        /// Gets the resource CurrentHotKey.
        /// </summary>
        public string CurrentHotKey => SettingsGeneralUserControl.SettingsGeneralUserControl.CurrentHotKey;

        /// <summary>
        /// Gets the resource HotKey.
        /// </summary>
        public string HotKey => SettingsGeneralUserControl.SettingsGeneralUserControl.HotKey;

        /// <summary>
        /// Gets the resource HotKeyPopupHelpText.
        /// </summary>
        public string HotKeyPopupHelpText => SettingsGeneralUserControl.SettingsGeneralUserControl.HotKeyPopupHelpText;

        /// <summary>
        /// Gets the resource HotKeyPopup_Accept.
        /// </summary>
        public string HotKeyPopup_Accept => SettingsGeneralUserControl.SettingsGeneralUserControl.HotKeyPopup_Accept;

        /// <summary>
        /// Gets the resource HotKeyPopup_Description1.
        /// </summary>
        public string HotKeyPopup_Description1 => SettingsGeneralUserControl.SettingsGeneralUserControl.HotKeyPopup_Description1;

        /// <summary>
        /// Gets the resource HotKeyPopup_Description2.
        /// </summary>
        public string HotKeyPopup_Description2 => SettingsGeneralUserControl.SettingsGeneralUserControl.HotKeyPopup_Description2;

        /// <summary>
        /// Gets the resource HotKeyPopup_Description3.
        /// </summary>
        public string HotKeyPopup_Description3 => SettingsGeneralUserControl.SettingsGeneralUserControl.HotKeyPopup_Description3;

        /// <summary>
        /// Gets the resource Language.
        /// </summary>
        public string Language => SettingsGeneralUserControl.SettingsGeneralUserControl.Language;

        /// <summary>
        /// Gets the resource MouseGesture.
        /// </summary>
        public string MouseGesture => SettingsGeneralUserControl.SettingsGeneralUserControl.MouseGesture;

        /// <summary>
        /// Gets the resource MouseGesture_Description.
        /// </summary>
        public string MouseGesture_Description => SettingsGeneralUserControl.SettingsGeneralUserControl.MouseGesture_Description;

        /// <summary>
        /// Gets the resource PasteBarPosition.
        /// </summary>
        public string PasteBarPosition => SettingsGeneralUserControl.SettingsGeneralUserControl.PasteBarPosition;

        /// <summary>
        /// Gets the resource PasteBarPosition_Bottom.
        /// </summary>
        public string PasteBarPosition_Bottom => SettingsGeneralUserControl.SettingsGeneralUserControl.PasteBarPosition_Bottom;

        /// <summary>
        /// Gets the resource PasteBarPosition_Top.
        /// </summary>
        public string PasteBarPosition_Top => SettingsGeneralUserControl.SettingsGeneralUserControl.PasteBarPosition_Top;

        /// <summary>
        /// Gets the resource RestoreDefault.
        /// </summary>
        public string RestoreDefault => SettingsGeneralUserControl.SettingsGeneralUserControl.RestoreDefault;

        /// <summary>
        /// Gets the resource RestoreDefault_Confirm.
        /// </summary>
        public string RestoreDefault_Confirm => SettingsGeneralUserControl.SettingsGeneralUserControl.RestoreDefault_Confirm;

        /// <summary>
        /// Gets the resource RestoreDefault_Confirmation.
        /// </summary>
        public string RestoreDefault_Confirmation => SettingsGeneralUserControl.SettingsGeneralUserControl.RestoreDefault_Confirmation;

        /// <summary>
        /// Gets the resource StartWithWindows.
        /// </summary>
        public string StartWithWindows => SettingsGeneralUserControl.SettingsGeneralUserControl.StartWithWindows;

        #endregion
    }

    internal class SettingsNotificationsUserControlStrings : ViewModelBase
    {
        #region Properties

        /// <summary>
        /// Gets the resource CreditCard.
        /// </summary>
        public string CreditCard => SettingsNotificationsUserControl.SettingsNotificationsUserControl.CreditCard;

        /// <summary>
        /// Gets the resource Password.
        /// </summary>
        public string Password => SettingsNotificationsUserControl.SettingsNotificationsUserControl.Password;

        /// <summary>
        /// Gets the resource SyncFailed.
        /// </summary>
        public string SyncFailed => SettingsNotificationsUserControl.SettingsNotificationsUserControl.SyncFailed;

        #endregion
    }

    internal class SettingsSecurityUserControlStrings : ViewModelBase
    {
        #region Properties

        /// <summary>
        /// Gets the resource AddIgnoreFromApps.
        /// </summary>
        public string AddIgnoreFromApps => SettingsSecurityUserControl.SettingsSecurityUserControl.AddIgnoreFromApps;

        /// <summary>
        /// Gets the resource CreditCard.
        /// </summary>
        public string CreditCard => SettingsSecurityUserControl.SettingsSecurityUserControl.CreditCard;

        /// <summary>
        /// Gets the resource CreditCard_Description.
        /// </summary>
        public string CreditCard_Description => SettingsSecurityUserControl.SettingsSecurityUserControl.CreditCard_Description;

        /// <summary>
        /// Gets the resource DisableSync.
        /// </summary>
        public string DisableSync => SettingsSecurityUserControl.SettingsSecurityUserControl.DisableSync;

        /// <summary>
        /// Gets the resource DisableSync_Description.
        /// </summary>
        public string DisableSync_Description => SettingsSecurityUserControl.SettingsSecurityUserControl.DisableSync_Description;

        /// <summary>
        /// Gets the resource IgnoreFromApps.
        /// </summary>
        public string IgnoreFromApps => SettingsSecurityUserControl.SettingsSecurityUserControl.IgnoreFromApps;

        /// <summary>
        /// Gets the resource IgnoreFromApps_Delete.
        /// </summary>
        public string IgnoreFromApps_Delete => SettingsSecurityUserControl.SettingsSecurityUserControl.IgnoreFromApps_Delete;

        /// <summary>
        /// Gets the resource IgnoreFromApps_DeleteHelpText.
        /// </summary>
        public string IgnoreFromApps_DeleteHelpText => SettingsSecurityUserControl.SettingsSecurityUserControl.IgnoreFromApps_DeleteHelpText;

        /// <summary>
        /// Gets the resource Passwords.
        /// </summary>
        public string Passwords => SettingsSecurityUserControl.SettingsSecurityUserControl.Passwords;

        /// <summary>
        /// Gets the resource Passwords_Description.
        /// </summary>
        public string Passwords_Description => SettingsSecurityUserControl.SettingsSecurityUserControl.Passwords_Description;

        #endregion
    }

    internal class SettingsSynchronizationUserControlStrings : ViewModelBase
    {
        #region Properties

        /// <summary>
        /// Gets the resource Confirm.
        /// </summary>
        public string Confirm => SettingsSynchronizationUserControl.SettingsSynchronizationUserControl.Confirm;

        /// <summary>
        /// Gets the resource Connect.
        /// </summary>
        public string Connect => SettingsSynchronizationUserControl.SettingsSynchronizationUserControl.Connect;

        /// <summary>
        /// Gets the resource ConnectionProblem.
        /// </summary>
        public string ConnectionProblem => SettingsSynchronizationUserControl.SettingsSynchronizationUserControl.ConnectionProblem;

        /// <summary>
        /// Gets the resource Description.
        /// </summary>
        public string Description => SettingsSynchronizationUserControl.SettingsSynchronizationUserControl.Description;

        /// <summary>
        /// Gets the resource Disconnect.
        /// </summary>
        public string Disconnect => SettingsSynchronizationUserControl.SettingsSynchronizationUserControl.Disconnect;

        /// <summary>
        /// Gets the resource MeteredConnection.
        /// </summary>
        public string MeteredConnection => SettingsSynchronizationUserControl.SettingsSynchronizationUserControl.MeteredConnection;

        /// <summary>
        /// Gets the resource Minutes.
        /// </summary>
        public string Minutes => SettingsSynchronizationUserControl.SettingsSynchronizationUserControl.Minutes;

        /// <summary>
        /// Gets the resource Name.
        /// </summary>
        public string Name => SettingsSynchronizationUserControl.SettingsSynchronizationUserControl.Name;

        /// <summary>
        /// Gets the resource Provider.
        /// </summary>
        public string Provider => SettingsSynchronizationUserControl.SettingsSynchronizationUserControl.Provider;

        /// <summary>
        /// Gets the resource SynchronizeEvery.
        /// </summary>
        public string SynchronizeEvery => SettingsSynchronizationUserControl.SettingsSynchronizationUserControl.SynchronizeEvery;

        /// <summary>
        /// Gets the resource SyncNow.
        /// </summary>
        public string SyncNow => SettingsSynchronizationUserControl.SettingsSynchronizationUserControl.SyncNow;

        /// <summary>
        /// Gets the resource UnlinkConfirmation.
        /// </summary>
        public string UnlinkConfirmation => SettingsSynchronizationUserControl.SettingsSynchronizationUserControl.UnlinkConfirmation;

        /// <summary>
        /// Gets the resource FileNotSynchronized.
        /// </summary>
        public string FileNotSynchronized => SettingsSynchronizationUserControl.SettingsSynchronizationUserControl.FileNotSynchronized;

        #endregion
    }

    internal class SettingsWindowStrings : ViewModelBase
    {
        #region Properties

        /// <summary>
        /// Gets the resource Close.
        /// </summary>
        public string Close => SettingsWindow.SettingsWindow.Close;

        /// <summary>
        /// Gets the resource Close_AccessibilityHelp.
        /// </summary>
        public string Close_AccessibilityHelp => SettingsWindow.SettingsWindow.Close_AccessibilityHelp;

        /// <summary>
        /// Gets the resource Close_AccessibilityKey.
        /// </summary>
        public string Close_AccessibilityKey => SettingsWindow.SettingsWindow.Close_AccessibilityKey;

        /// <summary>
        /// Gets the resource Section_About.
        /// </summary>
        public string Section_About => SettingsWindow.SettingsWindow.Section_About;

        /// <summary>
        /// Gets the resource Section_Data.
        /// </summary>
        public string Section_Data => SettingsWindow.SettingsWindow.Section_Data;

        /// <summary>
        /// Gets the resource Section_General.
        /// </summary>
        public string Section_General => SettingsWindow.SettingsWindow.Section_General;

        /// <summary>
        /// Gets the resource Section_Notifications.
        /// </summary>
        public string Section_Notifications => SettingsWindow.SettingsWindow.Section_Notifications;

        /// <summary>
        /// Gets the resource Section_Security.
        /// </summary>
        public string Section_Security => SettingsWindow.SettingsWindow.Section_Security;

        /// <summary>
        /// Gets the resource Section_Synchronization.
        /// </summary>
        public string Section_Synchronization => SettingsWindow.SettingsWindow.Section_Synchronization;

        /// <summary>
        /// Gets the resource WindowAutomationName.
        /// </summary>
        public string WindowAutomationName => SettingsWindow.SettingsWindow.WindowAutomationName;

        /// <summary>
        /// Gets the resource WindowTitle.
        /// </summary>
        public string WindowTitle => SettingsWindow.SettingsWindow.WindowTitle;

        #endregion
    }
}