//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipboardZanager.Strings.FirstStartWindow {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FirstStartWindow {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FirstStartWindow() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClipboardZanager.Strings.FirstStartWindow.FirstStartWindow", typeof(FirstStartWindow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it !.
        /// </summary>
        internal static string GotIt {
            get {
                return ResourceManager.GetString("GotIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to paste a data.
        /// </summary>
        internal static string HowToPaste_Title {
            get {
                return ResourceManager.GetString("HowToPaste_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use ClipboardZanager, copy a data, then press &quot;Alt + V&quot; to open the paste bar and select a data to paste..
        /// </summary>
        internal static string HowToPaste_TitleHelpText {
            get {
                return ResourceManager.GetString("HowToPaste_TitleHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ClipboardZanager.
        /// </summary>
        internal static string HowToPaste_Use {
            get {
                return ResourceManager.GetString("HowToPaste_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration completed.
        /// </summary>
        internal static string MigrationCompleted {
            get {
                return ResourceManager.GetString("MigrationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration failed.
        /// </summary>
        internal static string MigrationFailed {
            get {
                return ResourceManager.GetString("MigrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrating data in progress....
        /// </summary>
        internal static string MigrationInProgress {
            get {
                return ResourceManager.GetString("MigrationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you use a password manager software, you might not want to keep the copied login and password. That&apos;s why you can now choose an application which will be ignored by ClipboardZanager.
        ///You can change the list bellow, later, in the application&apos;s settings..
        /// </summary>
        internal static string Security_Description {
            get {
                return ResourceManager.GetString("Security_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety first.
        /// </summary>
        internal static string Security_Title {
            get {
                return ResourceManager.GetString("Security_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be connected, synchronize ClipboardZanager with a personal Cloud storage service, backup your data and retrieve them on another PC, Smartphone and Tablet.
        ///
        ///A lot of settings are available in your new clipboard manager, don&apos;t be shy, check them in a few seconds..
        /// </summary>
        internal static string Synchronization_Description {
            get {
                return ResourceManager.GetString("Synchronization_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data, at any time, any place.
        /// </summary>
        internal static string Synchronization_Title {
            get {
                return ResourceManager.GetString("Synchronization_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        internal static string Welcome_SelectLanguage {
            get {
                return ResourceManager.GetString("Welcome_SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To personnalize your settings, do a right click on the icon in the Task Bar..
        /// </summary>
        internal static string Welcome_Text {
            get {
                return ResourceManager.GetString("Welcome_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to ClipboardZanager !.
        /// </summary>
        internal static string Welcome_Title {
            get {
                return ResourceManager.GetString("Welcome_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s new in ClipboardZanager.
        /// </summary>
        internal static string WhatsNew_Title {
            get {
                return ResourceManager.GetString("WhatsNew_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First start wizard.
        /// </summary>
        internal static string WindowAutomationName {
            get {
                return ResourceManager.GetString("WindowAutomationName", resourceCulture);
            }
        }
    }
}
