//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipboardZanager.Strings.MainWindow {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainWindow {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindow() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClipboardZanager.Strings.MainWindow.MainWindow", typeof(MainWindow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClipboardZanager.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems that you just copied a credit card number. By security, we did not kept it.
        ///Copy it again if you want to keep it anyway..
        /// </summary>
        internal static string CreditCardDetected_Text {
            get {
                return ResourceManager.GetString("CreditCardDetected_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card detected.
        /// </summary>
        internal static string CreditCardDetected_Title {
            get {
                return ResourceManager.GetString("CreditCardDetected_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems that you just copied a credit card number, and we kept it. Change the settings to avoid it..
        /// </summary>
        internal static string CreditCardDetectedButSaved_Text {
            get {
                return ResourceManager.GetString("CreditCardDetectedButSaved_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card detected.
        /// </summary>
        internal static string CreditCardDetectedButSaved_Title {
            get {
                return ResourceManager.GetString("CreditCardDetectedButSaved_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it !.
        /// </summary>
        internal static string CreditCardSaved_Text {
            get {
                return ResourceManager.GetString("CreditCardSaved_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card detected.
        /// </summary>
        internal static string CreditCardSaved_Title {
            get {
                return ResourceManager.GetString("CreditCardSaved_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next step.
        /// </summary>
        internal static string FlipView_Next {
            get {
                return ResourceManager.GetString("FlipView_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the next step.
        /// </summary>
        internal static string FlipView_NextHelpText {
            get {
                return ResourceManager.GetString("FlipView_NextHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous step.
        /// </summary>
        internal static string FlipView_Previous {
            get {
                return ResourceManager.GetString("FlipView_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the previous step.
        /// </summary>
        internal static string FlipView_PreviousHelpText {
            get {
                return ResourceManager.GetString("FlipView_PreviousHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Menu_Paste_Text {
            get {
                return ResourceManager.GetString("Menu_Paste_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste a data from the clipboard.
        /// </summary>
        internal static string Menu_Paste_Tooltip {
            get {
                return ResourceManager.GetString("Menu_Paste_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string Menu_Quit_Text {
            get {
                return ResourceManager.GetString("Menu_Quit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit the application.
        /// </summary>
        internal static string Menu_Quit_Tooltip {
            get {
                return ResourceManager.GetString("Menu_Quit_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Menu_Settings_Text {
            get {
                return ResourceManager.GetString("Menu_Settings_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the application&apos;s settings.
        /// </summary>
        internal static string Menu_Settings_Tooltip {
            get {
                return ResourceManager.GetString("Menu_Settings_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize now.
        /// </summary>
        internal static string Menu_Synchronize_Text {
            get {
                return ResourceManager.GetString("Menu_Synchronize_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize now the data with the Cloud.
        /// </summary>
        internal static string Menu_Synchronize_Tooltip {
            get {
                return ResourceManager.GetString("Menu_Synchronize_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you decide to quit ClipboardZanager, your computer will loose its capacity to conserve datas copied in the clipboard. Do you want to continue?.
        /// </summary>
        internal static string Message_Quit {
            get {
                return ResourceManager.GetString("Message_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems that you just copied a password. By security, we did not kept it.
        ///Copy it again if you want to keep it anyway..
        /// </summary>
        internal static string PasswordDetected_Text {
            get {
                return ResourceManager.GetString("PasswordDetected_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password detected.
        /// </summary>
        internal static string PasswordDetected_Title {
            get {
                return ResourceManager.GetString("PasswordDetected_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems that you just copied a password, and we kept it. Change the settings to avoid it..
        /// </summary>
        internal static string PasswordDetectedButSaved_Text {
            get {
                return ResourceManager.GetString("PasswordDetectedButSaved_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password detected.
        /// </summary>
        internal static string PasswordDetectedButSaved_Title {
            get {
                return ResourceManager.GetString("PasswordDetectedButSaved_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it !.
        /// </summary>
        internal static string PasswordSaved_Text {
            get {
                return ResourceManager.GetString("PasswordSaved_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password detected.
        /// </summary>
        internal static string PasswordSaved_Title {
            get {
                return ResourceManager.GetString("PasswordSaved_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The synchronization has failed because of the connection, authentication to the service, or an internal error..
        /// </summary>
        internal static string SynchronizationFailed_Text {
            get {
                return ResourceManager.GetString("SynchronizationFailed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization failed.
        /// </summary>
        internal static string SynchronizationFailed_Title {
            get {
                return ResourceManager.GetString("SynchronizationFailed_Title", resourceCulture);
            }
        }
    }
}
