//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipboardZanager.Strings.SettingsSecurityUserControl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsSecurityUserControl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsSecurityUserControl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClipboardZanager.Strings.SettingsSecurityUserControl.SettingsSecurityUserControl", typeof(SettingsSecurityUserControl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an application to ignore.
        /// </summary>
        internal static string AddIgnoreFromApps {
            get {
                return ResourceManager.GetString("AddIgnoreFromApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not keep credit card numbers.
        /// </summary>
        internal static string CreditCard {
            get {
                return ResourceManager.GetString("CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to detect a copied text that looks like a credit card number, and avoid to keep it in memory for safety..
        /// </summary>
        internal static string CreditCard_Description {
            get {
                return ResourceManager.GetString("CreditCard_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable by default passwords and credit cards cloud synchronization..
        /// </summary>
        internal static string DisableSync {
            get {
                return ResourceManager.GetString("DisableSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the copied data is marked as a password or a credit card, the synchronization with the cloud will be disabled by default..
        /// </summary>
        internal static string DisableSync_Description {
            get {
                return ResourceManager.GetString("DisableSync_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore the copied data from the following applications.
        /// </summary>
        internal static string IgnoreFromApps {
            get {
                return ResourceManager.GetString("IgnoreFromApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string IgnoreFromApps_Delete {
            get {
                return ResourceManager.GetString("IgnoreFromApps_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Del to delete the selected item from the list of ignored applications..
        /// </summary>
        internal static string IgnoreFromApps_DeleteHelpText {
            get {
                return ResourceManager.GetString("IgnoreFromApps_DeleteHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not keep passwords.
        /// </summary>
        internal static string Passwords {
            get {
                return ResourceManager.GetString("Passwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to detect a copied text that looks like a password from your web browser, and avoid to keep it in memory for safety. As it is hard to detect if what you copy is a password or not because it is not excplicit, we suggest to keep in mind that this software can be wrong. If you see a password in your data and want to be safe, just remove it..
        /// </summary>
        internal static string Passwords_Description {
            get {
                return ResourceManager.GetString("Passwords_Description", resourceCulture);
            }
        }
    }
}
