//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipboardZanager.Strings.PasteBarWindow {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PasteBarWindow {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PasteBarWindow() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClipboardZanager.Strings.PasteBarWindow.PasteBarWindow", typeof(PasteBarWindow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esc.
        /// </summary>
        internal static string Close_AccessibilityKey {
            get {
                return ResourceManager.GetString("Close_AccessibilityKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put the data in the clipboard.
        /// </summary>
        internal static string Copy_Tooltip {
            get {
                return ResourceManager.GetString("Copy_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This data is a color : {0}.
        /// </summary>
        internal static string DataColor {
            get {
                return ResourceManager.GetString("DataColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This data is a set of copied files : {0}.
        /// </summary>
        internal static string DataFile {
            get {
                return ResourceManager.GetString("DataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a data that you can paste. Press Enter to paste the data..
        /// </summary>
        internal static string DataHelpText {
            get {
                return ResourceManager.GetString("DataHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This data is a picture..
        /// </summary>
        internal static string DataImage {
            get {
                return ResourceManager.GetString("DataImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This data is a link, titled {0}. The URL is {1}..
        /// </summary>
        internal static string DataLink {
            get {
                return ResourceManager.GetString("DataLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This data is a text : {0}.
        /// </summary>
        internal static string DataText {
            get {
                return ResourceManager.GetString("DataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This data has an unknown format..
        /// </summary>
        internal static string DataUnknow {
            get {
                return ResourceManager.GetString("DataUnknow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this data.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the selected data..
        /// </summary>
        internal static string Delete_ToolTip {
            get {
                return ResourceManager.GetString("Delete_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all.
        /// </summary>
        internal static string DeleteAll {
            get {
                return ResourceManager.GetString("DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all the data.
        /// </summary>
        internal static string DeleteAll_Tooltip {
            get {
                return ResourceManager.GetString("DeleteAll_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to proceed? You will definitly loose all these data..
        /// </summary>
        internal static string DeleteAllConfirm {
            get {
                return ResourceManager.GetString("DeleteAllConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to proceed? You will definitly loose this data..
        /// </summary>
        internal static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened while generating the thumbnail : {0}.
        /// </summary>
        internal static string ErrorGeneratingThumbnail {
            get {
                return ResourceManager.GetString("ErrorGeneratingThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add / Remove to favorites.
        /// </summary>
        internal static string Favorite {
            get {
                return ResourceManager.GetString("Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter only the files.
        /// </summary>
        internal static string Filter_Files {
            get {
                return ResourceManager.GetString("Filter_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter only the pictures.
        /// </summary>
        internal static string Filter_Images {
            get {
                return ResourceManager.GetString("Filter_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter only the links.
        /// </summary>
        internal static string Filter_Link {
            get {
                return ResourceManager.GetString("Filter_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter only the texts.
        /// </summary>
        internal static string Filter_Text {
            get {
                return ResourceManager.GetString("Filter_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More information.
        /// </summary>
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, there is no copied data....
        /// </summary>
        internal static string NoPresentData {
            get {
                return ResourceManager.GetString("NoPresentData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, nothing match your search....
        /// </summary>
        internal static string NoSearchResult {
            get {
                return ResourceManager.GetString("NoSearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown data.
        /// </summary>
        internal static string NoThumbnail {
            get {
                return ResourceManager.GetString("NoThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste the data in the foreground application.
        /// </summary>
        internal static string Paste_Tooltip {
            get {
                return ResourceManager.GetString("Paste_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search a data.
        /// </summary>
        internal static string SearchHelpText {
            get {
                return ResourceManager.GetString("SearchHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share this data.
        /// </summary>
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable the synchronization of this data with the cloud.
        /// </summary>
        internal static string Synchronize {
            get {
                return ResourceManager.GetString("Synchronize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}{2}.
        /// </summary>
        internal static string TimeSpan {
            get {
                return ResourceManager.GetString("TimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ago.
        /// </summary>
        internal static string TimeSpan_Ago {
            get {
                return ResourceManager.GetString("TimeSpan_Ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  days .
        /// </summary>
        internal static string TimeSpan_Days {
            get {
                return ResourceManager.GetString("TimeSpan_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  hour .
        /// </summary>
        internal static string TimeSpan_Hour {
            get {
                return ResourceManager.GetString("TimeSpan_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  hours .
        /// </summary>
        internal static string TimeSpan_Hours {
            get {
                return ResourceManager.GetString("TimeSpan_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just now.
        /// </summary>
        internal static string TimeSpan_LessThanAMinute {
            get {
                return ResourceManager.GetString("TimeSpan_LessThanAMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  minutes .
        /// </summary>
        internal static string TimeSpan_Minutes {
            get {
                return ResourceManager.GetString("TimeSpan_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        internal static string TimeSpan_Yesterday {
            get {
                return ResourceManager.GetString("TimeSpan_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste a data.
        /// </summary>
        internal static string WindowAutomationName {
            get {
                return ResourceManager.GetString("WindowAutomationName", resourceCulture);
            }
        }
    }
}
